### ISSUE TITLE
DB error 

### ISSUE THREAD

**Issue by Samueel991** [zad4y-fivem-scripts/esx_policejob#1]
Hey! I have one error in database when im trying to import esx_policejob.sql to database, it writes this error: and i really dont know how to fix it :( 

ERROR:
[SQL] query:

INSERT INTO `addon_account` (name, label, shared) VALUES
    ('society_police', 'Policia', 1)

MySQL said: Documentation
#1062 - Duplicate entry 'society_police' for key 'PRIMARY'

SCREEN OF ERROR: 
https://ctrlv.sk/iAHz

If somebody can help me, please answer me to comments.

**Comment by LittleKing205** [comment]
The dev has this line three times.
On import, you have to delete these two extra insert entry's.

**Comment by juanandresdavila** [comment]
I made a commit right now with few changes

**Comment by Ryzeeeev** [comment]
Hey ! Delete your SQL police job and insert:
The error comes from forgetting a comma.

INSERT INTO `addon_account` (name, label, shared) VALUES
    ('society_police', 'Policia', 1)
;

INSERT INTO `datastore` (name, label, shared) VALUES 
	('society_police','Policia',1)
;

INSERT INTO `jobs` (name, label, whitelisted) VALUES
    ('police', 'Policia', 1);

INSERT INTO `job_grades` (job_name, grade, name, label, salary, skin_male, skin_female) VALUES
    ('police',0,'recruit','Alumno', 20,'{}','{}'),
    ('police',1,'officer','Oficial I', 40,'{}','{}'),
    ('police',2,'sergeant','Oficial II', 60,'{}','{}'),
    ('police',3,'sergeant_chief','Sheriff', 80,'{}','{}'),
    ('police',4,'intendent','Inspector', 100,'{}','{}'),
    ('police',5,'lieutenant','Detective', 120,'{}','{}'),
    ('police',6,'chef','Comisario', 140,'{}','{}'),
    ('police',7,'boss','Super Intendente', 160,'{}','{}')
;

**Comment by juanandresdavila** [comment]
Ready.
