### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by tugapower0** [zad4y-fivem-scripts/esx_policejob#2]
Keep having an error on loading the config.

![imagem](https://user-images.githubusercontent.com/9769460/131244450-3c418963-9217-46ed-9f59-210a0abeb8f8.png)

**Comment by Sendoaa** [comment]
Do you know how to fix it? I have the same error

**Comment by juanandresdavila** [comment]
Those errors are this
```lua
for k,v in pairs(Config.PoliceStations) do
for k,v in pairs(Config.TeleportZones) do
```

I'll try to fix this

**Comment by RNXLtd** [comment]
Hey, I think I can help you with that. Would you mind sharing your config? Thanks

**Comment by juanandresdavila** [comment]
Fixed it
