### ISSUE TITLE
Cant see any markers

### ISSUE THREAD

**Issue by RoccoRP** [zad4y-fivem-scripts/esx_policejob#6]
i dont have any errors
and i cant see any markers like Cloakrooms , Armories , Vehicles ,Helicopters and BossActions 
none of them above ...

**Comment by dejaytalent** [comment]
Did you set you job ?? 
/setjob Id police 4

**Comment by RoccoRP** [comment]
> Did you set you job ?? /setjob Id police 4

yes

**Comment by dejaytalent** [comment]
Check out the coords of the cloakroom to check if your in the good building. Sometimes some police scripts use different building in the map. 
and make shure your other scripts running good as well. Because police jobs requires other scripts to work.  Good luck!
